services:
  couchbase:
    image: couchbase:enterprise-7.6.5
    container_name: couchbase-ai
    hostname: couchbase.local
    extra_hosts:
      - couchbase.local:127.0.0.1
    ports:
      - "8091-8097:8091-8097"
      - "9123:9123"
      - "11210:11210"
      - "11280:11280"
      - "18091-18097:18091-18097"
    restart: unless-stopped
